### ISSUE TITLE
Error encountered when running the project following README (downloaded from github)

### ISSUE THREAD

**Issue by lucky20020327** [FloridSleeves/LLMDebugger#15]
I'm running the project following the instructions in README and error occurs:

```
./run_simple.sh humaneval gpt-3.5-turbo-0125 test
INFO 10-11 15:03:16 importing.py:10] Triton not installed; certain GPU-related functions will not be available.
WARNING 10-11 15:03:16 _custom_ops.py:18] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Traceback (most recent call last):
  File ".../LLMDebugger/programming/main.py", line 3, in <module>
    from ldb import run_ldb
  File ".../LLMDebugger/programming/ldb.py", line 2, in <module>
    from generators import PyGenerator, model_factory
  File ".../LLMDebugger/programming/generators/__init__.py", line 1, in <module>
    from .py_generate import PyGenerator
  File ".../LLMDebugger/programming/generators/py_generate.py", line 1, in <module>
    from .model import ModelBase, message_to_str
  File ".../LLMDebugger/programming/generators/model.py", line 4, in <module>
    from vllm import LLM, SamplingParams
  File ".../anaconda3/envs/ldb/lib/python3.10/site-packages/vllm/__init__.py", line 6, in <module>
    from vllm.entrypoints.llm import LLM
  File ".../anaconda3/envs/ldb/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 8, in <module>
    from vllm.entrypoints.chat_utils import (ChatCompletionMessageParam,
  File ".../anaconda3/envs/ldb/lib/python3.10/site-packages/vllm/entrypoints/chat_utils.py", line 17, in <module>
    from openai.types.chat import (ChatCompletionContentPartRefusalParam,
ImportError: cannot import name 'ChatCompletionContentPartRefusalParam' from 'openai.types.chat' (.../anaconda3/envs/ldb/lib/python3.10/site-packages/openai/types/chat/__init__.py)
```

I'm running the code on Mac(M2). The version of the openai package(1.12.0) is the same as required in requirements.txt.

**Comment by CaoAnda** [comment]
`pip install vllm==0.5.0`, and then solved.
